services:
  - type: web
    name: stockify-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000

  - type: web
    name: stockify-frontend
    plan: free
    runtime: static
    buildCommand: npm install && npm run build
    publishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://REPLACE_WITH_BACKEND_URL.onrender.com
      - key: REACT_APP_DASHBOARD_URL
        value: https://REPLACE_WITH_DASHBOARD_URL.onrender.com

  - type: web
    name: stockify-dashboard
    plan: free
    runtime: static
    buildCommand: npm install && npm run build
    publishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://REPLACE_WITH_BACKEND_URL.onrender.com
      - key: REACT_APP_FRONTEND_URL
        value: https://REPLACE_WITH_FRONTEND_URL.onrender.com
